<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%> 
<%@ page import ="java.sql.*" %>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Flight Registration Portal</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
/* Style the body */
body {
  font-family: Arial;
  margin: 0;
}

/* Header/Logo Title */
.header {
 
  text-align: center;
  background: #1abc9c;
  color: white;
  font-size: 30px;
}

/* Page Content */
.content {padding:20px;}
</style>
</head>
<body>

<div class="header">
  <h1>Welcome Admin!</h1>
  
</div>
   
<form action="Reservations.jsp" method=“POST”>

Search Reservations by flightNumber: <input type="text" name="FlightNumber" ><br>
Search Reservations by Name: <input type="text" name="Name" ><br>
<input type="submit" value="search">
</form>



List all the flights from a given airport: 
<br>
	<form method="post" action="airportQuery.jsp">
		<select name="APID" size=1>
			<option value="EWR">EWR</option>
			<option value="JFK">JFK</option>
			<option value="SEA">SEA</option>
			<option value="LGA">LGA</option>
			<option value="IIL">IIL</option>
		</select>&nbsp;<br> <input type="submit" value="submit">
	</form>
	
	 Obtain a sales report for a particular month:
	 <br>
	<form method="post" action="monthSalesQuery.jsp">
		<select name="Month" size=1>
			<option value="01">Jan</option>
			<option value="02">Feb</option>
			<option value="03">Mar</option>
			<option value="04">Apr</option>
			<option value="05">May</option>
			<option value="06">Jun</option>
			<option value="07">Jul</option>
			<option value="08">Aug</option>
			<option value="09">Sep</option>
			<option value="10">Oct</option>
			<option value="11">Nov</option>
			<option value="12">Dec</option>
		</select>&nbsp;<br> <input type="submit" value="submit">
	</form>
	
	<br>
	
	 <form method="post" action="GeneratedRevenue.jsp">
     Produce a summary listing of revenue generated by a particular:
 <br><input type="radio" name="command" value="1"/>Flight
  <br>
  <input type="radio" name="command" value="2"/>Airline
  <br>
  <input type="radio" name="command" value="3"/>Customer
   <br> Enter name of Flight, Airline or Customer : <input type="text" name="Name" ><br>
  <br>
  <input type="submit" value="submit" />
</form>
<br>

<% Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection con = DriverManager.getConnection("jdbc:mysql://cs336db.cunxqv1yfwcg.us-east-2.rds.amazonaws.com:3306/cs336","admin", "password123");
Statement st = con.createStatement();
ResultSet rs=st.executeQuery("select * from account");
out.print("<table>");

//make a row
out.print("<tr>");
//make a column
out.print("<td>");
//print out column header
out.print("Email"+"  ");
out.print("</td>");
//make a column
out.print("<td>");
out.print("Password"+"  ");
out.print("</td>");
//make a column
out.print("<td>");
out.print("First_Name"+"  ");
out.print("</td>");
out.print("<td>");
out.print("Last_Name"+"  ");
out.print("</td>");
out.print("<td>");
out.print("Address"+"  ");
out.print("</td>");
out.print("<td>");
out.print("Account_type"+"  ");
out.print("</td>");
out.print("</tr>");
while (rs.next()) {
	//make a row
	out.print("<tr>");
	//make a column
	out.print("<td>");
	//Print out current email:
	out.print(rs.getString("email"));
	out.print("</td>");
	out.print("<td>");
	//Print out current password:
	out.print(rs.getString("password"));
	out.print("</td>");
	out.print("<td>");
	//Print out current first_name
	out.print(rs.getString("fname"));
	out.print("</td>");
	out.print("<td>");
	//Print out current last_name
	out.print(rs.getString("lname"));
	out.print("</td>");
	out.print("<td>");
	//Print out current address
	out.print(rs.getString("address"));
	out.print("</td>");
	out.print("<td>");
	//Print out current account_type
	out.print(rs.getString("accountcol"));
	out.print("</td>");
	out.print("</tr>");

}
out.print("</table>");
   %>


<br>Add/Edit information for a customer/customer representative:
<br>(If account already exists information will be updated)
<br>
	<form method="post" action="change.jsp">
	<table>
	<tr>    
	<td>Email</td><td><input type="text" name="email"></td>
	</tr>
	<tr>
	<td>Password</td><td><input type="text" name="password"></td>
	</tr>
	<tr>
	<td>First_Name</td><td><input type="text" name="fname"></td>
	</tr>
	<tr>
	<td>Last_Name</td><td><input type="text" name="lname"></td>
	</tr>
	<tr>
	<td>Address</td><td><input type="text" name="address"></td>
	</tr>
	<tr>
	<td>Account_Type</td><td><input type="text" name="accountcol"></td>
	</tr>
	</table>
	<input type="submit" name="action" value="Add/Update" />
    
	</form>
<br>


Alternatively, enter the email for the account which you wish to delete:
<br>


	<form method="POST">
	
	<input name="email" type="text" placeholder="email" />
	<button>Delete</button>
	</form>
<br>
<%
//Class.forName("com.mysql.jdbc.Driver").newInstance();
//Connection con = DriverManager.getConnection("jdbc:mysql://cs336db.cunxqv1yfwcg.us-east-2.rds.amazonaws.com:3306/cs336","admin", "password123");
Statement stmnt = con.createStatement();
ResultSet set;
String Email=request.getParameter("email");
String query = String.format("SELECT * FROM account WHERE email = \"%s\" ", Email);
set = stmnt.executeQuery(query);
if (set.next()) {
	query=String.format("DELETE FROM account WHERE email = \"%s\" ", Email);
	stmnt.executeUpdate(query);
	out.println("sucessfully deleted !");
}
con.close();
%>

<form method="POST" action=ActiveCustomer.jsp>
	
	<button>Find out which customer generated most total revenue</button>
	</form>
	
	<form method="POST" action=ActiveFlights.jsp>
	
	
	<button>Produce a list of most active flights</button>
</form>



 
   
</body>
<a href="logout.jsp">Logout</a>
</html>